server:
  port: 8083

spring:
  application:
    name: warehouse
  config:
    import: "configserver:http://config-server:8888"
  cloud:
    config:
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 6000
      discovery:
        enabled: true
        serviceId: config-server
  datasource:
    url: jdbc:postgresql://smart_home_db:5432/smart_home_db?currentSchema=warehouse
    username: user
    password: password

grpc:
  server:
    port: 9093

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${random.value}