logging:
  level:
    ru.yandex.practicum.telemetry: trace
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.springframework.jdbc.datasource.init: DEBUG

spring:
  sql:
    init:
      mode: always
      platform: postgresql
      schema-locations: classpath:schema-shopping-cart.sql
  datasource:
    url: jdbc:postgresql://localhost:5432/smart_home_db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: shopping_cart