spring:
  application:
    name: analyzer
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6541/smarthome
    username: smarthome
    password: smarthome
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  kafka:
    hub-consumer:
      bootstrap-servers: localhost:9092
      group-id: analyzer-hub-event-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: ru.practicum.telemetry.deserialization.HubEventDeserializer
      enable-auto-commit: false
    snapshot-consumer:
      bootstrap-servers: localhost:9092
      group-id: analyzer-snapshot-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: ru.practicum.telemetry.deserialization.SensorsSnapshotDeserializer
      enable-auto-commit: false
kafka:
  topics:
    hubs: telemetry.hubs.v1
    snapshots: telemetry.snapshots.v1
grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
logging:
  level:
    root: INFO
    ru.yandex.practicum.telemetry.analyzer: DEBUG